[package]
name = "gorillas-rs"
version = "0.1.0"
authors = ["nodef0 <d2isgreat@gmail.com>"]
edition = "2018"

[dependencies]
quicksilver = { version = "0.3.18", default-features = false, features = ["collisions", "fonts"] }
rand = { version = "0.7.0", features = ["stdweb"] }
